# Format the LaTeX table introducing the sample

This notebook has a very simple and limited purpose, to construct a correctly formatted table of the sources in the LoVoCCS sample, with basic properties - this essentially is what we use in papers to mostly represent the knowledge we had going in to the analyses (i.e. few newly measured properties).

## Import Statements

In [19]:
import pandas as pd
import numpy as np
import os

## Checking that another X-LoVoCCS repository is present

This notebook relies on the LoVoCCS observation summaries created in the X-LoVoCCS-Data repository (which contains all the notebooks necessary to recreate the LoVoCCS X-ray dataset) - thus we need to ensure that the repository is where we expect it to be before this notebook continues (this is mostly in case anyone ever wishes to recreate all of our analyses):

In [20]:
if not os.path.exists("../../../X-LoVoCCS-Data/"):
    raise FileNotFoundError("We require the X-LoVoCCS-Data repository to be cloned into the same "\
                            "parent folder as the X-LoVoCCS-Analyses directory.")
else:
    cov_summ_path = "../../../X-LoVoCCS-Data/outputs/summary_files/"

## Loading data files

Important considerations for this dataset:

* We only need the base X-LoVoCCS sample file and the X-ray mission coverage file from this repository.
* However we also need some observation archive summary files from the X-LoVoCCS-Data repository.

### X-LoVoCCS-I base sample

In [2]:
xlovoccs_base = pd.read_csv("../../sample_files/X-LoVoCCSI.csv")
xlovoccs_base.insert(0, 'name', xlovoccs_base['LoVoCCSID'].apply(lambda x: "LoVoCCS-" + str(x)))
xlovoccs_base.head(6)

,name,LoVoCCSID,parent_LoVoCCSID,Name,start_ra,start_dec,MCXC_Redshift,MCXC_R500,MCXC_RA,MCXC_DEC,manual_xray_ra,manual_xray_dec,MCXC_Lx500_0.1_2.4
0,LoVoCCS-1,1,1,A2029,227.734300,5.745471,0.0766,1.3344,227.73000,5.720000,227.734300,5.745471,8.726709e+44
1,LoVoCCS-2,2,2,A401,44.740000,13.580000,0.0739,1.2421,44.74000,13.580000,NaN,NaN,6.088643e+44
2,LoVoCCS-4,4,4,A85,10.458750,-9.301944,0.0555,1.2103,10.45875,-9.301944,NaN,NaN,5.100085e+44
3,LoVoCCS-5,5,5,A3667,303.157313,-56.845978,0.0556,1.1990,303.13000,-56.830000,303.157313,-56.845978,4.871933e+44
4,LoVoCCS-7,7,7,A3827,330.480000,-59.950000,0.0980,1.1367,330.48000,-59.950000,NaN,NaN,4.204419e+44
5,LoVoCCS-9,9,9,A3266,67.830487,-61.447401,0.0589,1.1485,67.85000,-61.440000,67.830487,-61.447401,3.977333e+44

### X-LoVoCCS coverage measurements

In [3]:
xlovoccs_xcov_frac = pd.read_csv("../../outputs/result_files/misc/mission_coverage_fractions.csv")
xlovoccs_xcov_frac.head(6)

,name,xmm_pointed_MCXC_R500,xmm_pointed_0.3Mpc,xmm_pointed_0.5Mpc,xmm_pointed_1.0Mpc,xmm_pointed_2.0Mpc,chandra_MCXC_R500,chandra_0.3Mpc,chandra_0.5Mpc,chandra_1.0Mpc,...,suzaku_MCXC_R500,suzaku_0.3Mpc,suzaku_0.5Mpc,suzaku_1.0Mpc,suzaku_2.0Mpc,erosita_all_sky_de_dr1_MCXC_R500,erosita_all_sky_de_dr1_0.3Mpc,erosita_all_sky_de_dr1_0.5Mpc,erosita_all_sky_de_dr1_1.0Mpc,erosita_all_sky_de_dr1_2.0Mpc
0,LoVoCCS-1,1.00,1.0,1.0,1.0,0.97,1.00,1.0,1.0,1.00,...,1.00,1.0,1.00,1.00,0.99,0.0,0.0,0.0,0.0,0.0
1,LoVoCCS-2,1.00,1.0,1.0,1.0,0.98,1.00,1.0,1.0,1.00,...,0.39,0.0,0.18,0.36,0.43,0.0,0.0,0.0,0.0,0.0
2,LoVoCCS-4,0.99,1.0,1.0,1.0,0.86,1.00,1.0,1.0,1.00,...,0.54,1.0,0.91,0.66,0.33,0.0,0.0,0.0,0.0,0.0
3,LoVoCCS-5,1.00,1.0,1.0,1.0,0.82,0.96,1.0,1.0,0.99,...,0.88,1.0,1.00,0.95,0.57,1.0,1.0,1.0,1.0,1.0
4,LoVoCCS-7,1.00,1.0,1.0,1.0,0.98,0.69,1.0,1.0,0.75,...,0.00,0.0,0.00,0.00,0.00,1.0,1.0,1.0,1.0,1.0
5,LoVoCCS-9,1.00,1.0,1.0,1.0,0.90,0.70,1.0,1.0,0.78,...,0.00,0.0,0.00,0.00,0.00,1.0,1.0,1.0,1.0,1.0

### X-LoVoCCS numbers of X-ray observations

In [29]:
xlovoccs_num_obs = pd.read_csv(cov_summ_path + "each_cluster_obs_num.csv")
xlovoccs_num_obs['parent_LoVoCCSID'] = xlovoccs_num_obs['name'].apply(lambda x: int(x.split('-')[-1]))
del xlovoccs_num_obs['name']
xlovoccs_num_obs.head(6)

,xmm_pointed,chandra,rosat_pointed_pspc,rosat_pointed_hri,rosat_all_sky,swift_xrt,asca,suzaku,nustar_pointed,erosita_all_sky_de_dr1,parent_LoVoCCSID
0,24,59,4,5,1,23,6,11,3,0,1
1,1,1,1,0,2,78,1,0,1,2,10
2,0,0,0,0,1,0,0,0,0,1,108
3,14,10,5,4,1,25,1,1,1,2,11
4,3,3,0,0,1,0,0,0,0,2,119
5,2,1,1,1,1,4,3,1,1,2,12

### X-LoVoCCS total exposure times

In [52]:
xlovoccs_exp_times = pd.read_csv(cov_summ_path + "total_xmm_exposures.csv")
xlovoccs_exp_times.head(6)

        name         exp
0  LoVoCCS-1  371.331 ks
1  LoVoCCS-2   32.201 ks
2  LoVoCCS-4  570.005 ks
3  LoVoCCS-5  218.902 ks
4  LoVoCCS-7   73.502 ks
5  LoVoCCS-9  824.974 ks

### Combining tables

In [53]:
xlovoccs_samp = pd.merge(xlovoccs_base, xlovoccs_xcov_frac, left_on='name', right_on='name', how='outer')
xlovoccs_samp = pd.merge(xlovoccs_samp, xlovoccs_num_obs, left_on='parent_LoVoCCSID', 
                         right_on='parent_LoVoCCSID', how='outer')
xlovoccs_samp = pd.merge(xlovoccs_samp, xlovoccs_exp_times, left_on='name', right_on='name', how='outer')
xlovoccs_samp['exp'] = xlovoccs_samp['exp'].fillna('0.0 ks')

# Makes sure that the order is correct
xlovoccs_samp = xlovoccs_samp.set_index('name').loc[xlovoccs_base['name'].values].reset_index(drop=False)
xlovoccs_samp.head(6)

,name,LoVoCCSID,parent_LoVoCCSID,Name,start_ra,start_dec,MCXC_Redshift,MCXC_R500,MCXC_RA,MCXC_DEC,...,chandra,rosat_pointed_pspc,rosat_pointed_hri,rosat_all_sky,swift_xrt,asca,suzaku,nustar_pointed,erosita_all_sky_de_dr1,exp
0,LoVoCCS-1,1,1,A2029,227.734300,5.745471,0.0766,1.3344,227.73000,5.720000,...,59,4,5,1,23,6,11,3,0,371.331 ks
1,LoVoCCS-2,2,2,A401,44.740000,13.580000,0.0739,1.2421,44.74000,13.580000,...,24,5,4,1,51,3,4,0,0,32.201 ks
2,LoVoCCS-4,4,4,A85,10.458750,-9.301944,0.0555,1.2103,10.45875,-9.301944,...,13,3,1,2,7,2,2,0,0,570.005 ks
3,LoVoCCS-5,5,5,A3667,303.157313,-56.845978,0.0556,1.1990,303.13000,-56.830000,...,13,2,1,2,9,3,5,1,1,218.902 ks
4,LoVoCCS-7,7,7,A3827,330.480000,-59.950000,0.0980,1.1367,330.48000,-59.950000,...,1,0,1,2,1,1,0,0,4,73.502 ks
5,LoVoCCS-9,9,9,A3266,67.830487,-61.447401,0.0589,1.1485,67.85000,-61.440000,...,2,2,2,1,5,1,0,3,2,824.974 ks

## Generating the table string

Here we generate the string of LaTeX code that can be copied in as the data body of the table:

In [5]:
round_pos = 3

In [56]:
lines = ""
for row_ind, row in xlovoccs_samp.iterrows():
    rel_name = row['Name']
    # Shorten the name
    if rel_name == "RX J0820.9+0751/RXC J0821.0+0751":
        rel_name = "RXC J0821.0+0751"
    
    # Add a dagger to match the caption - tells the reader that this one has another name
    if rel_name == 'RXC J2218.2-0350 East':
        rel_name = "RXC J2218.2-0350 East$^{\dagger}$"
    
    # Adds spaces around north/south/east/west/centre name components
    comps = {'North': r"\textit{North}", 'South': r"\textit{South}", 'East': r"\textit{East}", 
             'West': r"\textit{West}", 'Centre': r"\textit{Centre}"}
    
    # Never said I would make this auto table making beautiful...
    for comp, comp_rep in comps.items():
        # Adds spaces before the north/south/etc. component
        if comp in rel_name and " " + comp not in rel_name:
            rel_name = rel_name.replace(comp, ' '+comp_rep)
        elif comp in rel_name:
            rel_name = rel_name.replace(comp, comp_rep)

    rel_lov_id = row['LoVoCCSID']
    
    res_line = "{n} & {i} & ".format(n=rel_name, i=rel_lov_id)
    
    ra = round(row['start_ra'], round_pos)
    dec = round(row['start_dec'], round_pos)
    res_line += "{r} & {d} & ".format(r=ra, d=dec)
    
    res_line += "{} & ".format(round(row['MCXC_Redshift'], 3))
#     if not rel_lov_id[-1].isdigit() and rel_lov_id[-1] != 'A':
#         res_line += "- & "
#     else:
#         res_line += "{} & ".format(round(row['MCXC_R500'], 2))
    
    
    # For some clusters we are bolding their coverage fraction and adding a ddagger
    if row['xmm_pointed_1.0Mpc'] < 0.4:
        cov_str = r"\textbf{{{v}}}$^{{\ddagger}}$".format(v=row['xmm_pointed_1.0Mpc'])
    else:
        cov_str = row['xmm_pointed_1.0Mpc']
    
    res_line += "{tc} & {nxmm} & {texp} ".format(tc=cov_str, nxmm=row['xmm_pointed'], 
                                                 texp=round(float(row['exp'].split(' ')[0]), 1))
        
    res_line += '\\\ \n% \n'
    lines += res_line
print(lines)

A2029 & 1 & 227.734 & 5.745 & 0.077 & 1.0 & 24 & 371.3 \\
%
A401 & 2 & 44.74 & 13.58 & 0.074 & 1.0 & 8 & 32.2 \\
%
A85 & 4 & 10.459 & -9.302 & 0.056 & 1.0 & 8 & 570.0 \\
%
A3667 & 5 & 303.157 & -56.846 & 0.056 & 1.0 & 18 & 218.9 \\
%
A3827 & 7 & 330.48 & -59.95 & 0.098 & 1.0 & 5 & 73.5 \\
%
A3266 & 9 & 67.83 & -61.447 & 0.059 & 1.0 & 22 & 825.0 \\
%
A1651 & 10 & 194.84 & -4.19 & 0.085 & 1.0 & 1 & 23.4 \\
%
A754 & 11 & 137.28 & -9.67 & 0.054 & 1.0 & 14 & 235.4 \\
%
A3571 & 12 & 206.87 & -32.85 & 0.039 & 0.6 & 2 & 52.7 \\
%
A3112 & 13 & 49.49 & -44.24 & 0.075 & 1.0 & 4 & 497.5 \\
%
A399 & 14 & 44.46 & 13.05 & 0.072 & 1.0 & 8 & 27.6 \\
%
A2597 & 15 & 351.33 & -12.13 & 0.085 & 1.0 & 4 & 329.8 \\
%
A1650 & 18 & 194.671 & -1.757 & 0.085 & 1.0 & 1 & 96.8 \\
%
A3558 & 21 & 201.99 & -31.5 & 0.048 & 0.9 & 7 & 113.2 \\
%
A3695 & 22 & 308.694 & -35.824 & 0.089 & 1.0 & 1 & 28.7 \\
%
A3921 & 24 & 342.488 & -64.429 & 0.094 & 1.0 & 1 & 79.5 \\
%
A2426 & 26 & 333.636 & -10.372 & 0.098 & 1.0 & 2 & 31.3 \\
%
A3158 & 27 & 55.72 & -53.64 & 0.059 & 1.0 & 6 & 53.4 \\
%
RXC J1217.6+0339 & 28 & 184.42 & 3.66 & 0.077 & 1.0 & 5 & 62.9 \\
%
A2811 & 29 & 10.54 & -28.54 & 0.108 & 1.0 & 2 & 63.3 \\
%
A780 & 30 & 139.53 & -12.09 & 0.054 & 1.0 & 14 & 1078.1 \\
%
A2420 & 31 & 332.58 & -12.18 & 0.085 & 1.0 & 2 & 36.4 \\
%
A1285 & 33 & 172.592 & -14.576 & 0.107 & \textbf{0.35}$^{\ddagger}$ & 1 & 0.0 \\
%
A3911 & 35 & 341.577 & -52.729 & 0.097 & 1.0 & 1 & 69.0 \\
%
A2055 & 39 & 229.69 & 6.23 & 0.102 & 1.0 & 22 & 18.9 \\
%
A1750 \textit{Centre} & 41A & 202.707 & -1.862 & 0.085 & 1.0 & 1 & 79.8 \\
%
A1750 \textit{North} & 41B & 202.793 & -1.727 & 0.085 & 0.84 & 1 & 50.0 \\
%
A1750 \textit{South} & 41C & 202.557 & -2.094 & 0.085 & \textbf{0.21}$^{\ddagger}$ & 1 & 0.0 \\
%
A3822 & 42 & 328.538 & -57.855 & 0.076 & 1.0 & 4 & 47.2 \\
%
A2941 & 45 & 26.26 & -53.014 & 0.117 & 1.0 & 3 & 101.4 \\
%
A2440 \textit{Centre} & 46A & 335.988 & -1.583 & 0.091 & 1.0 & 1 & 70.3 \\
%
A2440 \textit{North} & 46B & 336.063 & -1.517 & 0.091 & 0.92 & 1 & 42.6 \\
%
A2440 \textit{South} & 46C & 335.949 & -1.65 & 0.091 & 1.0 & 1 & 75.5 \\
%
A1644 \textit{South} & 48A & 194.287 & -17.409 & 0.047 & 0.99 & 5 & 14.4 \\
%
A1644 \textit{North} & 48B & 194.455 & -17.273 & 0.05 & 0.97 & 5 & 22.0 \\
%
A1348 & 49 & 175.35 & -12.27 & 0.119 & 1.0 & 1 & 56.2 \\
%
RBS 1847 & 51 & 334.502 & -65.181 & 0.095 & 1.0 & 1 & 23.8 \\
%
RXC J1215.4-3900 & 55 & 183.858 & -39.027 & 0.119 & \textbf{0.0}$^{\ddagger}$ & 0 & 0.0 \\
%
A2351 & 58 & 323.568 & -13.439 & 0.09 & 1.0 & 2 & 25.6 \\
%
RXC J2218.2-0350 \textit{West} & 60A & 334.573 & -3.825 & 0.09 & 1.0 & 4 & 236.9 \\
%
RXC J2218.2-0350 \textit{East}$^{\dagger}$ & 60B & 334.667 & -3.78 & 0.09 & 1.0 & 4 & 275.9 \\
%
A2443 & 61 & 336.521 & 17.366 & 0.107 & 1.0 & 1 & 206.5 \\
%
A2050 & 63 & 229.08 & 0.1 & 0.118 & 1.0 & 3 & 92.4 \\
%
A1736 & 65 & 201.725 & -27.183 & 0.046 & 0.65 & 3 & 59.7 \\
%
A2384 \textit{North} & 66A & 328.091 & -19.546 & 0.094 & 0.79 & 1 & 21.8 \\
%
A2384 \textit{South} & 66B & 328.033 & -19.722 & 0.094 & 1.0 & 1 & 43.9 \\
%
A4059 & 67 & 359.26 & -34.76 & 0.048 & 0.78 & 4 & 516.0 \\
%
A3836 & 74 & 332.347 & -51.815 & 0.106 & 1.0 & 1 & 30.9 \\
%
A2533 & 75 & 346.81 & -15.224 & 0.111 & 1.0 & 1 & 29.1 \\
%
A2556 & 76 & 348.25 & -21.63 & 0.087 & 1.0 & 4 & 23.7 \\
%
A3126 & 80 & 52.16 & -55.71 & 0.085 & 1.0 & 2 & 28.1 \\
%
RXC J0049.4-2931 & 85 & 12.35 & -29.524 & 0.108 & 1.0 & 2 & 47.3 \\
%
A2554 & 89 & 348.08 & -21.504 & 0.111 & 1.0 & 4 & 11.9 \\
%
A2033 & 90 & 227.862 & 6.349 & 0.082 & 0.76 & 24 & 6.1 \\
%
A3395 \textit{North} & 93A & 96.867 & -54.439 & 0.051 & 0.83 & 3 & 70.5 \\
%
A3395 \textit{South} & 93B & 96.688 & -54.539 & 0.051 & 0.63 & 3 & 63.4 \\
%
A1606 & 94 & 191.15 & -11.993 & 0.096 & 1.0 & 3 & 38.3 \\
%
A2670 & 98 & 358.56 & -10.41 & 0.076 & 1.0 & 1 & 38.4 \\
%
A3532 & 99 & 194.334 & -30.363 & 0.055 & 0.96 & 9 & 18.2 \\
%
RXC J1139.4-3327 & 108 & 174.86 & -33.45 & 0.108 & \textbf{0.0}$^{\ddagger}$ & 0 & 0.0 \\
%
RXC J0821.0+0751 & 119 & 125.259 & 7.864 & 0.11 & 1.0 & 3 & 437.6 \\
%
A3128 & 121 & 52.466 & -52.581 & 0.062 & 1.0 & 3 & 169.7 \\
%
A1023 & 122 & 157.0 & -6.8 & 0.118 & \textbf{0.0}$^{\ddagger}$ & 0 & 0.0 \\
%
A3528 & 123 & 193.67 & -29.22 & 0.054 & 0.95 & 9 & 36.4 \\
%
A761 & 131 & 137.651 & -10.581 & 0.092 & 1.0 & 17 & 17.8 \\
%
A3825 & 134 & 329.605 & -60.414 & 0.075 & 1.0 & 5 & 38.9 \\
%

<>:10: SyntaxWarning: invalid escape sequence '\d'
<>:48: SyntaxWarning: invalid escape sequence '\ '
<>:10: SyntaxWarning: invalid escape sequence '\d'
<>:48: SyntaxWarning: invalid escape sequence '\ '
/tmp/ipykernel_1940142/3617346078.py:10: SyntaxWarning: invalid escape sequence '\d'
  rel_name = "RXC J2218.2-0350 East$^{\dagger}$"
/tmp/ipykernel_1940142/3617346078.py:48: SyntaxWarning: invalid escape sequence '\ '
  res_line += '\\\ \n% \n'